server:
  port: 8123

spring:
  application:
    name: codeAgent
  profiles:
    active: local
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_agent?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  
  # 邮件配置
  mail:
    # 邮件配置信息
    # 163邮箱的SMTP服务器配置
    protocol: smtp  # 使用的邮件协议
    default-encoding: UTF-8  # 默认编码格式
    test-connection: true # 启动时是否测试连接
    host: smtp.163.com  # SMTP服务器地址
    port: 465 # 端口号（默认为SMTP的标准端口）
    username: cmh22408@163.com # 发件人邮箱地址
    password: QDTXLMQLCARYHZYS  # 发件人邮箱密码
    properties:
      # 邮件客户端属性配置
      mail.smtp.auth: true  # 启用SMTP身份验证
      mail.smtp.starttls.enable: true  # 启用STARTTLS协议
      mail.smtp.starttls.required: true  # 要求使用STARTTLS协议
      mail.smtp.socketFactory.port: 465  # SSL连接使用的端口号
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory  # SSL连接的SocketFactory类
      mail.smtp.socketFactory.fallback: false  # SSL连接失败时不回退到非加密连接

# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 开启Mybatis二级缓存，默认为 true
    cache-enabled: false
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: ASSIGN_ID
      # 逻辑删除字段名
      logic-delete-field: deleted
      # 逻辑删除全局值（默认 1、表示已删除）
      logic-delete-value: 1
      # 逻辑未删除全局值（默认为 0、表示未删除）
      logic-not-delete-value: 0

# Sa-Token配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 是否从 cookie 中读取 token
  is-read-cookie: false
  # 是否从 header 中读取 token
  is-read-header: true
  # 是否从 body 中读取 token
  is-read-body: false
  # token前缀
  token-prefix: "Bearer"
  # 是否在初始化配置时打印版本字符画
  is-print: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.code.codeagent.controller

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表

# 日志配置
logging:
  level:
    com.code.codeagent: INFO
    org.springframework.web.servlet.resource: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"